=== DozerMapper/Dozer/src/site/resources/dtd/dozerbeanmapping.dtd
<!ELEMENT mappings ( configuration?, mapping* ) >

<!ELEMENT configuration ( is-accessible?, stop-on-errors?, date-format?, wildcard?, bean-factory?, custom-converters*, copy-by-references*, allowed-exceptions* ) >

<!ELEMENT mapping ( class-a | class-b | field | field-exclude )* >
<!ATTLIST mapping date-format CDATA #IMPLIED >
<!ATTLIST mapping stop-on-errors CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping wildcard CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping bean-factory CDATA #IMPLIED>
<!ATTLIST mapping type (one-way | bi-directional) "bi-directional" >
<!ATTLIST mapping map-id CDATA #IMPLIED>
<!ATTLIST mapping is-accessible CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-a ( #PCDATA ) >
<!ATTLIST class-a bean-factory CDATA #IMPLIED >
<!ATTLIST class-a factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-a map-set-method CDATA #IMPLIED >
<!ATTLIST class-a map-get-method CDATA #IMPLIED >
<!ATTLIST class-a create-method CDATA #IMPLIED >
<!ATTLIST class-a map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-a map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-b ( #PCDATA ) >
<!ATTLIST class-b bean-factory CDATA #IMPLIED >
<!ATTLIST class-b factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-b map-set-method CDATA #IMPLIED >
<!ATTLIST class-b map-get-method CDATA #IMPLIED >
<!ATTLIST class-b create-method CDATA #IMPLIED >
<!ATTLIST class-b map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-b map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT field ( a, b ,a-hint?, b-hint? ) >
<!ATTLIST field relationship-type (cumulative  | non-cumulative  ) "cumulative" >
<!ATTLIST field type (one-way | bi-directional) "bi-directional" >
<!ATTLIST field map-id CDATA #IMPLIED>
<!ATTLIST field copy-by-reference CDATA #IMPLIED> <!-- (true | false ) "false" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST field custom-converter CDATA #IMPLIED>

<!ELEMENT field-exclude ( a, b ) >
<!ATTLIST field-exclude type (one-way | bi-directional) "bi-directional" >

<!ELEMENT a ( #PCDATA ) >
<!ATTLIST a date-format CDATA #IMPLIED >
<!ATTLIST a type (iterate | generic ) "generic" >
<!ATTLIST a set-method CDATA #IMPLIED >
<!ATTLIST a get-method CDATA #IMPLIED >
<!ATTLIST a key CDATA #IMPLIED >
<!ATTLIST a map-set-method CDATA #IMPLIED >
<!ATTLIST a map-get-method CDATA #IMPLIED >
<!ATTLIST a is-accessible CDATA #IMPLIED >
<!ATTLIST a create-method CDATA #IMPLIED>

<!ELEMENT b ( #PCDATA ) >
<!ATTLIST b date-format CDATA #IMPLIED >
<!ATTLIST b type (iterate | generic ) "generic" >
<!ATTLIST b set-method CDATA #IMPLIED >
<!ATTLIST b get-method CDATA #IMPLIED >
<!ATTLIST b key CDATA #IMPLIED >
<!ATTLIST b map-set-method CDATA #IMPLIED >
<!ATTLIST b map-get-method CDATA #IMPLIED >
<!ATTLIST b is-accessible CDATA #IMPLIED >
<!ATTLIST b create-method CDATA #IMPLIED>

<!ELEMENT a-hint ( #PCDATA ) >
<!ELEMENT b-hint ( #PCDATA ) >
<!ELEMENT stop-on-errors ( #PCDATA ) >
<!ELEMENT date-format ( #PCDATA ) >
<!ELEMENT map-null ( #PCDATA ) >
<!ELEMENT map-empty-string ( #PCDATA ) >
<!ELEMENT wildcard ( #PCDATA ) >
<!ELEMENT bean-factory ( #PCDATA ) >
<!ELEMENT custom-converters ( converter+ ) >

<!ELEMENT converter ( class-a, class-b ) >
<!ATTLIST converter type CDATA #REQUIRED >

<!ELEMENT copy-by-references ( copy-by-reference+ ) >
<!ELEMENT copy-by-reference ( #PCDATA ) >
<!ELEMENT is-accessible ( #PCDATA ) >
<!ELEMENT allowed-exceptions ( exception+ ) >
<!ELEMENT exception ( #PCDATA ) >

=== DozerMapper/Dozer/src/main/mappings/overridemapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
  "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">

<mappings>

  <configuration>
     <stop-on-errors>false</stop-on-errors>
     <date-format>MM/dd/yyyy HH:mm</date-format> <!-- default date-format will apply to all class maps unless the class mapping explicitly overrides it -->
     <wildcard>false</wildcard> <!-- default wildcard policy that will apply to all class maps unless the class mapping explicitly overrides it -->
          
     <copy-by-references>
       <copy-by-reference>net.sf.dozer.util.mapping.vo.NoExtendBaseObjectGlobalCopyByReference</copy-by-reference>
     </copy-by-references>
          
  </configuration>

  <mapping stop-on-errors="true">
    <class-a>net.sf.dozer.util.mapping.vo.FurtherTestObject</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.Car</class-b>    
  </mapping>

  <mapping wildcard="true">
    <class-a>net.sf.dozer.util.mapping.vo.SuperSuperSuperClass</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SuperSuperSuperClassPrime</class-b>    
  </mapping>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.TestObject</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.TestObjectPrime</class-b>
    
    <field copy-by-reference="false">
      <a>globalCopyByReference</a>
      <b>globalCopyByReferencePrime</b>
    </field>    
  </mapping>
  
</mappings>

=== DozerMapper/Dozer/src/main/mappings/xmlBeansMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <configuration>
     <stop-on-errors>true</stop-on-errors>
     <date-format>MM/dd/yyyy HH:mm</date-format> <!-- default dateformat will apply to all class maps unless the class mapping explicitly overrides it -->
     <wildcard>true</wildcard> <!-- default wildcard policy that will apply to all class maps unless the class mapping explicitly overrides it -->     
  </configuration>
  
  <mapping  wildcard="false">
    <class-a>net.sf.dozer.util.mapping.vo.TestObject</class-a>
    <class-b bean-factory="net.sf.dozer.util.mapping.factory.XMLBeanFactory">net.sf.dozer.util.mapping.vo.GetWeatherByZipCodeDocument</class-b>

    <field>
      <a>one</a>
      <b>GetWeatherByZipCode.zipCode</b>
    </field>    
  </mapping>   

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.Child</class-a>
    <class-b bean-factory="net.sf.dozer.util.mapping.factory.XMLBeanFactory">net.pmonks.xml.dozer.test.ChildType</class-b>

    <field>
      <a>name</a>
      <b>name</b>
    </field>
  </mapping>

  <mapping  wildcard="false">
    <class-a>net.sf.dozer.util.mapping.vo.TestObject</class-a>
    <class-b bean-factory="net.sf.dozer.util.mapping.factory.XMLBeanFactory">net.sf.dozer.util.mapping.vo.GetWeatherByZipCodeResponseDocument</class-b>

    <field>
      <a>setToArray</a>
      <b>GetWeatherByZipCodeResponse.WeatherDataArray</b>
    </field>    
  </mapping>   

</mappings>

=== DozerMapper/Dozer/src/main/mappings/fieldCustomConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.SimpleObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SimpleObjPrime2</class-b>    
    <field custom-converter="net.sf.dozer.util.mapping.converters.StringAppendCustomConverter">
      <a>field1</a>
      <b>field1Prime</b>
    </field>
  </mapping>   
  
  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.map.CustomMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SimpleObj</class-b>    
    <field custom-converter="net.sf.dozer.util.mapping.converters.StringAppendCustomConverter">
      <a map-get-method="getValue" key="fieldA">this</a>
      <b>field1</b>
    </field>
  </mapping>   

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.map.MapToProperty</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SimpleObj</class-b>    
    <field custom-converter="net.sf.dozer.util.mapping.converters.StringAppendCustomConverter">
      <a key="fieldA">hashMap</a>
      <b>field1</b>
    </field>
  </mapping>   
  

</mappings>

=== DozerMapper/Dozer/src/main/mappings/infiniteLoopMapping.xml
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
  "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">

<mappings>
  <mapping stop-on-errors="true">
    <class-a>net.sf.dozer.util.mapping.vo.LoopObjectParent</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.LoopObjectParentPrime</class-b>
    <field>
      <a>attribute</a>
      <b>attributePrime</b>
    </field>
    <field>
      <a>child</a>
      <b>childPrime</b>
      <a-hint>net.sf.dozer.util.mapping.vo.LoopObjectChild</a-hint>
      <b-hint>net.sf.dozer.util.mapping.vo.LoopObjectChildPrime</b-hint>
    </field>
  </mapping>
</mappings>

=== DozerMapper/Dozer/src/main/mappings/recursivemappings.xml
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
  "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
	<mapping wildcard="true">
		<class-a>net.sf.dozer.util.mapping.recursive.TestClassA</class-a>
		<class-b>net.sf.dozer.util.mapping.recursive.TestClassAPrime</class-b>
		<field>
			<a>subs</a>
			<b>subs</b>
			<a-hint>net.sf.dozer.util.mapping.recursive.TestClassB</a-hint>
			<b-hint>net.sf.dozer.util.mapping.recursive.TestClassBPrime</b-hint>
		</field>
	</mapping>
	
	<mapping wildcard="true">
		<class-a>net.sf.dozer.util.mapping.recursive.TestClassAA</class-a>
		<class-b>net.sf.dozer.util.mapping.recursive.TestClassAAPrime</class-b>
	</mapping>
	<mapping wildcard="false" map-id="minimal">
		<class-a>net.sf.dozer.util.mapping.recursive.TestClassA</class-a>
		<class-b>net.sf.dozer.util.mapping.recursive.TestClassAPrime</class-b>
		<field>
			<a>nom</a>
			<b>nom</b>
		</field>
		<field map-id="minimal">
			<a>subs</a>
			<b>subs</b>
			<a-hint>net.sf.dozer.util.mapping.recursive.TestClassB</a-hint>
			<b-hint>net.sf.dozer.util.mapping.recursive.TestClassBPrime</b-hint>
		</field>
	</mapping>
</mappings>

=== DozerMapper/Dozer/src/main/mappings/primitiveArrayToListMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
 
 <mapping>
   <class-a>net.sf.dozer.util.mapping.vo.PrimitiveArrayObj</class-a>
   <class-b>net.sf.dozer.util.mapping.vo.PrimitiveArrayObjPrime</class-b>
   <field>
     <a>field1</a>
     <b>field1</b>
   </field>        
 </mapping> 

 <mapping map-id="primitiveToArrayUsingHint">
   <class-a>net.sf.dozer.util.mapping.vo.PrimitiveArrayObj</class-a>
   <class-b>net.sf.dozer.util.mapping.vo.PrimitiveArrayObjPrime</class-b>
   <field>
     <a>field1</a>
     <b>field1</b>
     <b-hint>java.lang.String</b-hint> 
   </field>        
 </mapping> 

</mappings>

=== DozerMapper/Dozer/src/main/mappings/global-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
    "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
  <configuration>
  <copy-by-references>
     <copy-by-reference>
       net.sf.dozer.util.mapping.copybyreference.Reference
     </copy-by-reference>
  </copy-by-references>
  </configuration>
  <mapping> 
    <class-a>net.sf.dozer.util.mapping.copybyreference.TestA</class-a>
    <class-b>net.sf.dozer.util.mapping.copybyreference.TestB</class-b>   
    <field>
      <a>oneA</a>
      <b>oneB</b>
    </field>
  </mapping>  


</mappings>

=== DozerMapper/Dozer/src/main/mappings/setMappingWithUpperCaseFieldName.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.set.SomeDTO</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.set.SomeVO</class-b>
    <field>
      <a>Field2</a>
      <b>Field2</b>
      <a-hint>net.sf.dozer.util.mapping.vo.set.SomeOtherDTO</a-hint>
      <b-hint>net.sf.dozer.util.mapping.vo.set.SomeOtherVO</b-hint>
    </field>
  </mapping>

</mappings>
