=== DozerMapper/Dozer/src/site/resources/dtd/dozerbeanmapping.dtd
<!ELEMENT mappings ( configuration?, mapping* ) >

<!ELEMENT configuration ( is-accessible?, stop-on-errors?, date-format?, wildcard?, bean-factory?, custom-converters*, copy-by-references*, allowed-exceptions* ) >

<!ELEMENT mapping ( class-a | class-b | field | field-exclude )* >
<!ATTLIST mapping date-format CDATA #IMPLIED >
<!ATTLIST mapping stop-on-errors CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping wildcard CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping bean-factory CDATA #IMPLIED>
<!ATTLIST mapping type (one-way | bi-directional) "bi-directional" >
<!ATTLIST mapping map-id CDATA #IMPLIED>
<!ATTLIST mapping is-accessible CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-a ( #PCDATA ) >
<!ATTLIST class-a bean-factory CDATA #IMPLIED >
<!ATTLIST class-a factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-a map-set-method CDATA #IMPLIED >
<!ATTLIST class-a map-get-method CDATA #IMPLIED >
<!ATTLIST class-a create-method CDATA #IMPLIED >
<!ATTLIST class-a map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-a map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-b ( #PCDATA ) >
<!ATTLIST class-b bean-factory CDATA #IMPLIED >
<!ATTLIST class-b factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-b map-set-method CDATA #IMPLIED >
<!ATTLIST class-b map-get-method CDATA #IMPLIED >
<!ATTLIST class-b create-method CDATA #IMPLIED >
<!ATTLIST class-b map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-b map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT field ( a, b ,a-hint?, b-hint? ) >
<!ATTLIST field relationship-type (cumulative  | non-cumulative  ) "cumulative" >
<!ATTLIST field type (one-way | bi-directional) "bi-directional" >
<!ATTLIST field map-id CDATA #IMPLIED>
<!ATTLIST field copy-by-reference CDATA #IMPLIED> <!-- (true | false ) "false" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST field custom-converter CDATA #IMPLIED>

<!ELEMENT field-exclude ( a, b ) >
<!ATTLIST field-exclude type (one-way | bi-directional) "bi-directional" >

<!ELEMENT a ( #PCDATA ) >
<!ATTLIST a date-format CDATA #IMPLIED >
<!ATTLIST a type (iterate | generic ) "generic" >
<!ATTLIST a set-method CDATA #IMPLIED >
<!ATTLIST a get-method CDATA #IMPLIED >
<!ATTLIST a key CDATA #IMPLIED >
<!ATTLIST a map-set-method CDATA #IMPLIED >
<!ATTLIST a map-get-method CDATA #IMPLIED >
<!ATTLIST a is-accessible CDATA #IMPLIED >
<!ATTLIST a create-method CDATA #IMPLIED>

<!ELEMENT b ( #PCDATA ) >
<!ATTLIST b date-format CDATA #IMPLIED >
<!ATTLIST b type (iterate | generic ) "generic" >
<!ATTLIST b set-method CDATA #IMPLIED >
<!ATTLIST b get-method CDATA #IMPLIED >
<!ATTLIST b key CDATA #IMPLIED >
<!ATTLIST b map-set-method CDATA #IMPLIED >
<!ATTLIST b map-get-method CDATA #IMPLIED >
<!ATTLIST b is-accessible CDATA #IMPLIED >
<!ATTLIST b create-method CDATA #IMPLIED>

<!ELEMENT a-hint ( #PCDATA ) >
<!ELEMENT b-hint ( #PCDATA ) >
<!ELEMENT stop-on-errors ( #PCDATA ) >
<!ELEMENT date-format ( #PCDATA ) >
<!ELEMENT map-null ( #PCDATA ) >
<!ELEMENT map-empty-string ( #PCDATA ) >
<!ELEMENT wildcard ( #PCDATA ) >
<!ELEMENT bean-factory ( #PCDATA ) >
<!ELEMENT custom-converters ( converter+ ) >

<!ELEMENT converter ( class-a, class-b ) >
<!ATTLIST converter type CDATA #REQUIRED >

<!ELEMENT copy-by-references ( copy-by-reference+ ) >
<!ELEMENT copy-by-reference ( #PCDATA ) >
<!ELEMENT is-accessible ( #PCDATA ) >
<!ELEMENT allowed-exceptions ( exception+ ) >
<!ELEMENT exception ( #PCDATA ) >

=== DozerMapper/Dozer/src/main/mappings/mapMapping2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

 <mapping map-id="caseA">
    <class-a>java.util.HashMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObjPrime</class-b>
 </mapping> 

 <mapping map-id="caseB">
    <class-a>java.util.HashMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObjPrime</class-b>
   <field-exclude>
     <a>field1</a>
     <b>field1</b>
   </field-exclude>
 </mapping> 

</mappings>

=== DozerMapper/Dozer/src/main/mappings/deepMappingWithIndexedFields.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
 
 <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.deep.SrcDeepObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.deep.DestDeepObj</class-b>
    <field>
      <a>srcNestedObj.srcNestedObj2.simpleObjects[0].field1</a>
      <b>dest2</b>
    </field>
 </mapping>

 <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.HeadOfHouseHold</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.Family</class-b>
    <field>
      <a>firstName</a>
      <b>familyMembers[0].firstName</b>
      <b-deep-index-hint>net.sf.dozer.util.mapping.vo.PersonalDetails</b-deep-index-hint>
    </field>
    <field>
      <a>lastName</a>
      <b>familyMembers[0].lastName</b>
      <b-deep-index-hint>net.sf.dozer.util.mapping.vo.PersonalDetails</b-deep-index-hint>
    </field>
    <field>
      <a>salary</a>
      <b>familyMembers[0].salary</b>
      <b-deep-index-hint>net.sf.dozer.util.mapping.vo.PersonalDetails</b-deep-index-hint>
    </field>
 
    <field>
      <a>petName</a>
      <b>pets[1].petName</b>
    </field>
    <field>
      <a>petAge</a>
      <b>pets[1].petAge</b>
    </field>
    <field>
      <a>offSpringName</a>
      <b>pets[1].offSpring[2].petName</b>
    </field>
   
   
   
 </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/nullFieldMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping map-null="false" map-empty-string="false">
    <class-a>net.sf.dozer.util.mapping.vo.AnotherTestObject</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.AnotherTestObjectPrime</class-b>
    <field>
      <a>field4</a>
      <b>to.one</b>
    </field>
  </mapping>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.TestObject</class-a>
    <class-b map-null="false" map-empty-string="false">net.sf.dozer.util.mapping.vo.TestObjectPrime2</class-b>
  </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/mapMapping3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.map.SimpleObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObjPrime</class-b>
  </mapping>

  <mapping>
    <class-a>java.util.HashMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.NestedObjPrime</class-b>
    <field-exclude>
      <a>field1</a>
      <b>field1</b>
    </field-exclude>
  </mapping>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.map.CustomMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SimpleObj</class-b>
    <field>
      <a map-get-method="getValue" map-set-method="putValue" key="fieldA" date-format="MM/dd/yyyy">this</a>
      <b>field5</b>
      <a-hint>java.lang.String</a-hint>
    </field>
  </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/arrayToStringCustomConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
  <configuration>
    <custom-converters>
      <converter type="net.sf.dozer.util.mapping.converters.StringAppendCustomConverter">
        <class-a>[Lnet.sf.dozer.util.mapping.vo.SimpleObj;</class-a>
        <class-b>java.lang.String</class-b>
      </converter>
    </custom-converters>
  </configuration>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.ArrayCustConverterObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.ArrayCustConverterObjPrime</class-b>
    <field>
      <a>field1</a>
      <b>field1Prime</b>
    </field>
  </mapping>
</mappings>

=== DozerMapper/Dozer/src/main/mappings/customfactorymapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <configuration>
    <stop-on-errors>true</stop-on-errors>
    <wildcard>true</wildcard>
    <bean-factory>net.sf.dozer.util.mapping.factories.SampleDefaultBeanFactory</bean-factory>
  </configuration>

  <!-- mapping level factory should override top level factory.  mapping level factory will get applied to both classes-->
  <mapping bean-factory="net.sf.dozer.util.mapping.factories.SampleCustomBeanFactory">
    <class-a>net.sf.dozer.util.mapping.vo.TestObject</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.TestObjectPrime</class-b>
    <field>
      <a>one</a>
      <b>onePrime</b>
    </field>
    <field>
      <a>three</a>
      <b>threePrime</b>
    </field>
    <field-exclude>
      <a>createdByFactoryName</a>
      <b>createdByFactoryName</b>
    </field-exclude>
  </mapping>

  <!-- class level factory should override top level and mapping level factory. -->
  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.InsideTestObject</class-a>
    <class-b bean-factory="net.sf.dozer.util.mapping.factories.SampleCustomBeanFactory2"
      factory-bean-id="someBeanId">
      net.sf.dozer.util.mapping.vo.InsideTestObjectPrime
    </class-b>
    <field-exclude>
      <a>createdByFactoryName</a>
      <b>createdByFactoryName</b>
    </field-exclude>
  </mapping>

  <mapping>
    <class-a bean-factory="net.sf.dozer.util.mapping.factories.SampleCustomBeanFactory3">
      net.sf.dozer.util.mapping.vo.MetalThingyIF
    </class-a>
    <class-b>net.sf.dozer.util.mapping.vo.Van</class-b>
  </mapping>


</mappings>

=== DozerMapper/Dozer/src/main/mappings/mapMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping map-id="caseA">
    <class-a>net.sf.dozer.util.mapping.vo.map.SimpleObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObjPrime</class-b>
    <field map-id="caseB">
      <a>nested2</a>
      <b>nested2</b>
    </field>

  </mapping>

  <mapping map-id="caseA2">
    <class-a>net.sf.dozer.util.mapping.vo.map.SimpleObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObjPrime</class-b>
    <field map-id="caseC">
      <a>nested2</a>
      <b>nested2</b>
    </field>

  </mapping>



  <mapping map-id="caseB">
    <class-a>java.util.HashMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.NestedObjPrime</class-b>
  </mapping>

  <mapping map-id="caseC">
    <class-a>java.util.HashMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.NestedObjPrime</class-b>
    <field-exclude>
      <a>field1</a>
      <b>field1</b>
    </field-exclude>
  </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/mapInterfaceMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.map.MapToMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.MapToMapPrime</class-b>

    <field>
      <a is-accessible="true">standardMapWithHint</a>
      <b is-accessible="true">standardMapWithHint</b>
      <a-hint>net.sf.dozer.util.mapping.vo.TestObject</a-hint>
      <b-hint>net.sf.dozer.util.mapping.vo.TestObjectPrime</b-hint>
    </field>

  </mapping>

</mappings>
