=== DozerMapper/Dozer/src/site/resources/dtd/dozerbeanmapping.dtd
<!ELEMENT mappings ( configuration?, mapping* ) >

<!ELEMENT configuration ( is-accessible?, stop-on-errors?, date-format?, wildcard?, bean-factory?, custom-converters*, copy-by-references*, allowed-exceptions* ) >

<!ELEMENT mapping ( class-a | class-b | field | field-exclude )* >
<!ATTLIST mapping date-format CDATA #IMPLIED >
<!ATTLIST mapping stop-on-errors CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping wildcard CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST mapping bean-factory CDATA #IMPLIED>
<!ATTLIST mapping type (one-way | bi-directional) "bi-directional" >
<!ATTLIST mapping map-id CDATA #IMPLIED>
<!ATTLIST mapping is-accessible CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-a ( #PCDATA ) >
<!ATTLIST class-a bean-factory CDATA #IMPLIED >
<!ATTLIST class-a factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-a map-set-method CDATA #IMPLIED >
<!ATTLIST class-a map-get-method CDATA #IMPLIED >
<!ATTLIST class-a create-method CDATA #IMPLIED >
<!ATTLIST class-a map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-a map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT class-b ( #PCDATA ) >
<!ATTLIST class-b bean-factory CDATA #IMPLIED >
<!ATTLIST class-b factory-bean-id CDATA #IMPLIED >
<!ATTLIST class-b map-set-method CDATA #IMPLIED >
<!ATTLIST class-b map-get-method CDATA #IMPLIED >
<!ATTLIST class-b create-method CDATA #IMPLIED >
<!ATTLIST class-b map-null CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST class-b map-empty-string CDATA #IMPLIED> <!-- (true | false ) "true" : if we don't make this CDATA the overidden flag is always true -->

<!ELEMENT field ( a, b ,a-hint?, b-hint? ) >
<!ATTLIST field relationship-type (cumulative  | non-cumulative  ) "cumulative" >
<!ATTLIST field type (one-way | bi-directional) "bi-directional" >
<!ATTLIST field map-id CDATA #IMPLIED>
<!ATTLIST field copy-by-reference CDATA #IMPLIED> <!-- (true | false ) "false" : if we don't make this CDATA the overidden flag is always true -->
<!ATTLIST field custom-converter CDATA #IMPLIED>

<!ELEMENT field-exclude ( a, b ) >
<!ATTLIST field-exclude type (one-way | bi-directional) "bi-directional" >

<!ELEMENT a ( #PCDATA ) >
<!ATTLIST a date-format CDATA #IMPLIED >
<!ATTLIST a type (iterate | generic ) "generic" >
<!ATTLIST a set-method CDATA #IMPLIED >
<!ATTLIST a get-method CDATA #IMPLIED >
<!ATTLIST a key CDATA #IMPLIED >
<!ATTLIST a map-set-method CDATA #IMPLIED >
<!ATTLIST a map-get-method CDATA #IMPLIED >
<!ATTLIST a is-accessible CDATA #IMPLIED >
<!ATTLIST a create-method CDATA #IMPLIED>

<!ELEMENT b ( #PCDATA ) >
<!ATTLIST b date-format CDATA #IMPLIED >
<!ATTLIST b type (iterate | generic ) "generic" >
<!ATTLIST b set-method CDATA #IMPLIED >
<!ATTLIST b get-method CDATA #IMPLIED >
<!ATTLIST b key CDATA #IMPLIED >
<!ATTLIST b map-set-method CDATA #IMPLIED >
<!ATTLIST b map-get-method CDATA #IMPLIED >
<!ATTLIST b is-accessible CDATA #IMPLIED >
<!ATTLIST b create-method CDATA #IMPLIED>

<!ELEMENT a-hint ( #PCDATA ) >
<!ELEMENT b-hint ( #PCDATA ) >
<!ELEMENT stop-on-errors ( #PCDATA ) >
<!ELEMENT date-format ( #PCDATA ) >
<!ELEMENT map-null ( #PCDATA ) >
<!ELEMENT map-empty-string ( #PCDATA ) >
<!ELEMENT wildcard ( #PCDATA ) >
<!ELEMENT bean-factory ( #PCDATA ) >
<!ELEMENT custom-converters ( converter+ ) >

<!ELEMENT converter ( class-a, class-b ) >
<!ATTLIST converter type CDATA #REQUIRED >

<!ELEMENT copy-by-references ( copy-by-reference+ ) >
<!ELEMENT copy-by-reference ( #PCDATA ) >
<!ELEMENT is-accessible ( #PCDATA ) >
<!ELEMENT allowed-exceptions ( exception+ ) >
<!ELEMENT exception ( #PCDATA ) >

=== DozerMapper/Dozer/src/main/mappings/indexMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.index.Mccoy</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.index.MccoyPrime</class-b>
    <field>
      <a>stringProperty</a>
      <b map-get-method="getValue" map-set-method="putValue" key="">fieldValueObjects[0]</b>
      <b-hint>net.sf.dozer.util.mapping.vo.FieldValue</b-hint>
    </field>
  </mapping>

  <mapping map-id="usingDestHint">
    <class-a>net.sf.dozer.util.mapping.vo.index.Mccoy</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.index.MccoyPrime</class-b>
    <field>
      <a>stringProperty</a>
      <b>fieldValueObjects[0]</b>
      <b-hint>net.sf.dozer.util.mapping.vo.FieldValue</b-hint>
    </field>
  </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/mapGetSetMethodMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping map-id="useCase1">
    <class-a map-get-method="getValue" map-set-method="putValue">net.sf.dozer.util.mapping.vo.map.CustomMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObj</class-b>    
    <field>
      <a key="fieldA">this</a>
      <b>field1</b>
    </field>
    <field>
      <a>this</a>
      <b>field2</b>
    </field>
    <field>
      <a key="fieldC">this</a>
      <b>field3</b>
    </field>
    <field>
      <a key="fieldD">this</a>
      <b>field4</b>
      <a-hint>java.lang.String</a-hint>
    </field>
    <field>
      <a key="fieldE" date-format="MM-dd-yyyy">this</a>
      <b>field5</b>
      <a-hint>java.lang.String</a-hint>
    </field>
  </mapping>   
  
  <mapping map-id="useCase2">
    <class-a>net.sf.dozer.util.mapping.vo.map.CustomMap</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.map.SimpleObj</class-b>    
    <field>
      <a map-get-method="getValue" map-set-method="putValue" key="fieldA">this</a>
      <b>field1</b>
    </field>
    <field>
      <a map-get-method="getValue" map-set-method="putValue">this</a>
      <b>field2</b>
    </field>
    <field>
      <a map-get-method="getValue" map-set-method="putValue" key="fieldC">this</a>
      <b>field3</b>
    </field>
    <field>
      <a map-get-method="getValue" map-set-method="putValue" key="fieldD">this</a>
      <b>field4</b>
      <a-hint>java.lang.String</a-hint>
    </field>
    <field>
      <a map-get-method="getValue" map-set-method="putValue" key="fieldE" date-format="MM-dd-yyyy">this</a>
      <b>field5</b>
      <a-hint>java.lang.String</a-hint>
    </field>
  </mapping>   
  
</mappings>

=== DozerMapper/Dozer/src/main/mappings/injectedCustomConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <configuration>
    <stop-on-errors>true</stop-on-errors>
    <wildcard>true</wildcard>
    <custom-converters>
      <converter type="net.sf.dozer.util.mapping.converters.InjectedCustomConverter">
        <class-a>net.sf.dozer.util.mapping.vo.Vehicle</class-a>
        <class-b>net.sf.dozer.util.mapping.vo.Vehicle</class-b>
      </converter>
    </custom-converters>
  </configuration>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/abstractMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
  "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">

<mappings>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.abstractinheritance.AbstractA</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.abstractinheritance.AbstractB</class-b>
    <field>
      <a>abstractAField</a>
      <b>abstractBField</b>
    </field>    
    <field-exclude>
      <a>abstractField1</a>
      <b>abstractField1</b>
    </field-exclude>    
  </mapping>
  
  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.abstractinheritance.A</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.abstractinheritance.B</class-b>
    <field>
      <a>fieldA</a>
      <b>fieldB</b>
    </field>    
  </mapping>

</mappings>

=== DozerMapper/Dozer/src/main/mappings/reference-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
    "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
  <mapping>
    <class-a>net.sf.dozer.util.mapping.copybyreference.TestA</class-a>
    <class-b>net.sf.dozer.util.mapping.copybyreference.TestB</class-b>
    <field>
      <a>oneA</a>
      <b>oneB</b>
    </field>
    <field copy-by-reference="true">
      <a>testReference</a>
      <b>testReference</b>
    </field>
  </mapping>
</mappings>

=== DozerMapper/Dozer/src/main/mappings/duplicateMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <configuration>
     <stop-on-errors>true</stop-on-errors>
     <date-format>MM/dd/yyyy HH:mm</date-format> <!-- default dateformat will apply to all class maps unless the class mapping explicitly overrides it -->
     <wildcard>true</wildcard> <!-- default wildcard policy that will apply to all class maps unless the class mapping explicitly overrides it -->
  </configuration>
  
  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.SuperSuperSuperClass</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SuperSuperSuperClassPrime</class-b>

    <field>
      <a>hydrate</a>
      <b>dehydrate</b>
    </field>        
  </mapping> 

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.SuperSuperSuperClass</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SuperSuperSuperClassPrime</class-b>

    <field>
      <a>hydrate</a>
      <b>dehydrate</b>
    </field>        
        
  </mapping> 
  
</mappings>

=== DozerMapper/Dozer/src/main/mappings/simpleCustomConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <configuration>
    <custom-converters>
      <converter type="net.sf.dozer.util.mapping.converters.StringAppendCustomConverter" >
        <class-a>java.lang.String</class-a>
        <class-b>java.lang.String</class-b>
      </converter>
      <converter type="net.sf.dozer.util.mapping.converters.InjectedCustomConverter" >
        <class-a>net.sf.dozer.util.mapping.vo.Vehicle</class-a>
        <class-b>net.sf.dozer.util.mapping.vo.Vehicle</class-b>
      </converter>
    </custom-converters>
  </configuration>

  <mapping>
    <class-a>net.sf.dozer.util.mapping.vo.SimpleObj</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.SimpleObjPrime2</class-b>    
    <field>
      <a>field1</a>
      <b>field1Prime</b>
    </field>
  </mapping>   
  
</mappings>

=== DozerMapper/Dozer/src/main/mappings/contextMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>

  <mapping map-id="caseA">
    <class-a>net.sf.dozer.util.mapping.vo.context.ContextMapping</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.context.ContextMappingPrime</class-b>
    <field-exclude>
      <a>loanNo</a>
      <b>loanNo</b>
    </field-exclude>
    <field map-id="caseC">
      <a>contextList</a>
      <b>contextList</b>
      <a-hint>net.sf.dozer.util.mapping.vo.context.ContextMappingNested</a-hint>
      <b-hint>net.sf.dozer.util.mapping.vo.context.ContextMappingNestedPrime</b-hint>
    </field>
  </mapping>

  <mapping map-id="caseB">
    <class-a>net.sf.dozer.util.mapping.vo.context.ContextMapping</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.context.ContextMappingPrime</class-b>
  </mapping>

  <mapping map-id="caseC">
    <class-a>net.sf.dozer.util.mapping.vo.context.ContextMappingNested</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.context.ContextMappingNestedPrime</class-b>
    <field-exclude>
      <a>loanNo</a>
      <b>loanNo</b>
    </field-exclude>
  </mapping>

  <mapping map-id="caseD">
    <class-a>net.sf.dozer.util.mapping.vo.context.ContextMappingNested</class-a>
    <class-b>net.sf.dozer.util.mapping.vo.context.ContextMappingNestedPrime</class-b>
  </mapping>


</mappings>
